# Use postgres/example user/password credentials
version: '3.1'

services:
  dynamodb:
    image: amazon/dynamodb-local
    # -sharedDb makes the nosql workbench able to see tables
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath .
    restart: always
    ports:
      - '8000:8000'