version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0

executors:
  node:
    docker:
      - image: circleci/node:lts

jobs:
  lint:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: NPM install
          command: |
            echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ./.npmrc
            if [ ! -d node_modules ]; then
              npm ci
            else
              echo "Skip npm ci"
            fi
      - save_cache:
          key: dependency-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run lint

  test:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: NPM install
          command: |
            echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ./.npmrc
            npm ci
      - run:
          name: prepare kms_key.yml
          command: |
            echo 'local: x' >> kms_key.yml
            echo 'dev: x' >> kms_key.yml
            echo 'test: x' >> kms_key.yml
            echo 'prod: x' >> kms_key.yml
      - run: npm run test:ci
      - run: npm run sls:package:dev

workflows:
  version: 2.1
  lint_and_test:
    jobs:
      - lint
      - test
